language: cpp
dist:     trusty
sudo:     required
notifications:
  email:  false
services:
  - docker
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: qt5-build

after_success:
  - echo "AFTER SUCCESS"

addons:
  artifacts: true
  paths:
    - wkhtmltox_0.13-alpha-$TRAVIS_BUILD_NUMBER.jessie_amd64.deb

matrix:
  include:

    - os:         linux
      env:        TARGET=system-qt5-linux
      addons:
        apt:
          packages:
          - libqt5webkit5-dev
          - libqt5xmlpatterns5-dev
          - libqt5svg5-dev

install:
- sed -i -e 's/    SYNCQT_OPTS=/    SYNCQT_OPTS=-quiet/g' qt/configure
- test -n "$CC"  && unset CC
- test -n "$CXX" && unset CXX
- git clone https://github.com/wkhtmltopdf/packaging.git ../packaging

script:
- >
    if   [[ $TARGET == "system-qt4-linux"   ]]; then qmake-qt4 CONFIG+=silent && make;
    elif [[ $TARGET == "system-qt5-linux"   ]]; then /usr/lib/x86_64-linux-gnu/qt5/bin/qmake CONFIG+=silent && make;
    elif [[ $TARGET == "custom-qt4-linux"   ]]; then ../packaging/build compile-docker stretch-amd64   $PWD ../build;
    elif [[ $TARGET == "custom-qt4-windows" ]]; then ../packaging/build compile-docker mxe-cross-win64 $PWD ../build;
    elif [[ $TARGET == "custom-qt4-osx"     ]]; then
        sudo -H pip install -q conan pyyaml --ignore-installed six && sudo gem install fpm --no-ri --no-rdoc && \
        sudo xcode-select --switch /Library/Developer/CommandLineTools && \
        MACOSX_DEPLOYMENT_TARGET=10.7 ../packaging/build vagrant macos-cocoa --clean --version - - $PWD;
    fi
- docker run --rm -v"$PWD":/tgt -w/tgt -v"$PWD/bin":/build/bin -v"$PWD/lib":/build/lib   -e XZ_OPT=-9 --user root:root tenzer/fpm -a amd64 -f -s dir -C /build --epoch 1 --version "0.13-alpha" --iteration "$TRAVIS_BUILD_NUMBER.jessie" --name "wkhtmltox" --description "convert HTML to PDF and various image formats using QtWebkit" --license "LGPLv3" --vendor "wkhtmltopdf"  --maintainer "Ashish Kulkarni <kulkarni.ashish@gmail.com>" --url "https://wkhtmltopdf.org/" --prefix "/usr/local" --category "utils" --depends libqt5webkit5 --depends ca-certificates --depends fontconfig --depends libc6 --depends libfreetype6 --depends libjpeg62-turbo --depends libpng12-0 --depends libssl1.0.0 --depends libstdc++6 --depends libx11-6 --depends libxcb1 --depends libxext6 --depends libxrender1 --depends xfonts-75dpi --depends xfonts-base --depends zlib1g -t deb --deb-compression xz --provides wkhtmltopdf --conflicts wkhtmltopdf --replaces wkhtmltopdf --deb-no-default-config-files
- docker run --rm -v"$PWD":/tgt -w/tgt -v"$PWD/bin":/build/bin -v"$PWD/lib":/build/lib -e XZ_OPT=-9 --user root:root tenzer/fpm -a amd64 -f -s dir -C /build --epoch 1 --version "0.13-alpha" --iteration "$TRAVIS_BUILD_NUMBER.stretch" --name "wkhtmltox" --description "convert HTML to PDF and various image formats using QtWebkit" --license "LGPLv3" --vendor "wkhtmltopdf"  --maintainer "Ashish Kulkarni <kulkarni.ashish@gmail.com>" --url "https://wkhtmltopdf.org/" --prefix "/usr/local" --category "utils" --depends libqt5webkit5 --depends ca-certificates --depends fontconfig --depends libc6 --depends libfreetype6 --depends libjpeg62-turbo --depends libpng16-16 --depends libssl1.1 --depends libstdc++6 --depends libx11-6 --depends libxcb1 --depends libxext6 --depends libxrender1 --depends xfonts-75dpi --depends xfonts-base --depends zlib1g -t deb --deb-compression xz --provides wkhtmltopdf --conflicts wkhtmltopdf --replaces wkhtmltopdf --deb-no-default-config-files
#- ../packaging/build package-docker jessie-amd64 $PWD
- rm -rf $PWD/src $PWD/qt
- mkdir -p $PWD/lib
- cp *.so* $PWD/lib/
- cp wkhtmltox_0.13-alpha-$TRAVIS_BUILD_NUMBER.jessie_amd64.deb wkhtmltox_0.13-alpha-nightly.jessie_amd64.deb
- cp wkhtmltox_0.13-alpha-$TRAVIS_BUILD_NUMBER.stretch_amd64.deb wkhtmltox_0.13-alpha-nightly.stretch_amd64.deb
- dpkg -c wkhtmltox_0.13-alpha-nightly.stretch_amd64.deb
